# Generated by Django 4.2 on 2023-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SequenceModel",
            fields=[
                ("sequence", models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
