# Generated by Django 4.2 on 2023-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplicator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequencemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sequencemodel",
            name="sequence",
            field=models.DateField(null=True),
        ),
    ]
