# Generated by Django 4.2 on 2023-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplicator", "0002_sequencemodel_id_alter_sequencemodel_sequence"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sequencemodel",
            constraint=models.UniqueConstraint(
                fields=("sequence",), name="unique_sequence"
            ),
        ),
    ]
