# Generated by Django 4.2 on 2023-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplicator", "0003_sequencemodel_unique_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencemodel",
            name="sequence",
            field=models.TextField(null=True),
        ),
    ]
